services:
  bulwark.auth:
    image: "lateflip/bulwark.auth:latest"
    env_file:
      - .env
    ports:
      - 8080:80
    depends_on:
      - mongodb
      - mailhog
  mongodb:
    image: "mongo:latest"
    ports:
      - 27017:27017
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - 1025:1025
      - 8025:8025
  